### ISSUE TITLE
外卖商家列表点击最后一个cell的展开按钮，查看更多标签，cell标题从番茄炒蛋变成干炸丸子的数据了，点击其他cell文字闪烁

### ISSUE THREAD

**Issue by BuddyLine** [Meituan-Dianping/Graver#31]
### Environment Details

* Graver version: 1.0.0
* iOS version: 12.1.4
* Xcode version: 10.1
1.演示代码中外卖商家列表点击最后一个cell的展开按钮，查看更多标签，cell标题从番茄炒蛋变成干炸丸子的数据了，点击其他cell文字闪烁,数据会乱掉。
2.美团外卖app中附近商家列表，点击展开箭头，cell展开，刷新列表,文字会闪烁
这个刷新列表，文字闪烁有没有好的解决方案？

**Comment by gerald8** [comment]
试下 master 上的代码呢？

**Comment by BuddyLine** [comment]
嗯，我下载是master上面的代码呀

**Comment by gerald8** [comment]
你上面写的是graver 1.0.0啊




            
            
                
                    
                            
                                
                            
                            
                                melowwx
                            
                    
                        
                            
                                    邮箱：melowwx@gmail.com
                            
                        
                
            
        


在2019年03月25日 22:47，BuddyLine 写道： 嗯，我下载是master上面的代码呀

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Meituan-Dianping/Graver","title":"Meituan-Dianping/Graver","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Meituan-Dianping/Graver"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BuddyLine in #31: 嗯，我下载是master上面的代码呀"}],"action":{"name":"View Issue","url":"https://github.com/Meituan-Dianping/Graver/issues/31#issuecomment-476229635"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Meituan-Dianping/Graver/issues/31#issuecomment-476229635",
"url": "https://github.com/Meituan-Dianping/Graver/issues/31#issuecomment-476229635",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BuddyLine** [comment]
我下载的是master分支上面的demo,然后pod 导入Graver，终端上面显示1.0.0

**Comment by RTiOS** [comment]
请更新最新代码尝试下~
